version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: "sleep 9999999"
    ports:
      - "20801:20800"
    volumes:
      - ./src:/code/
    init: true
  database:
    image: postgres:16.4-alpine3.20
    ports:
      - "5441:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test
networks:
  default:
    external:
      name: work_network
